import React from 'react'
import css from './Qualify.module.scss'
import nftImage from '../../../assets/index-page/nft-nft.png'
import clpImage from '../../../assets/index-page/clp-clp.png'
import circle from '../../../assets/index-page/circle.png'

const Qualify = (props) => {
    return (
        <div className={css.qualify}>
            <div className="container">
                <div className={css.inner}>
                    <div className={css.side}>
                        <div>
                            <h2 className={css.title}><span className={css.mark}>Two things</span> are required to qualify:</h2>
                            <div className={css.thing}>
                                <div className={css.circleContainer}>
                                    <img src={circle} className={css.circle} alt="" />
                                </div>
                                <p className={css.text}>NFTs from the <span className={css.mark}>CosmoLand</span> collection</p>
                            </div>
                        </div>
                        <img src={nftImage} className={css.nftImage} alt="" />
                    </div>
                    <div className={css.side}>
                        <img src={clpImage} className={css.clpImage} alt="" />
                        <div className={css.thing}>
                            <div className={css.circleContainer + ' ' + css.second}>
                                <img src={circle} className={css.circle} alt="" />
                            </div>
                            <p className={css.text}>CLP tokens generated by NFT from the <span className={css.mark}>CosmoLand</span> collection*</p>
                        </div>
                        <p className={css.additionalInfo}>*For the purchase of one NFT, you automatically
                            receive 183 CLP tokens, but If you participate in
                            the 14-day initial sale period, you will receive an
                            additional 183 tokens of the collection.</p>
                    </div>
                </div>
                <div className={css.inner + ' ' + css.check}>
                    <ul className={css.list}>
                        <li className={css.listItem}>Total result up to 366 collection's tokens in 10 years</li>
                        <li className={css.listItem}>Daily reward accrual</li>
                        <li className={css.listItem}>Minimum purchase amount from 1 USDC</li>
                        <li className={css.listItem}>Request withdrawal of reward at any time</li>
                        <li className={css.listItem}>Minimum exchange of the collection's tokens for USDC (Polygon blockchain) from any sum</li>
                    </ul>
                </div>
            </div>
        </div>
    )
}

export default Qualify